spring:
  application:
    name: SUBMISSION-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/submission_service
    username: root
    password: Aman@2002
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 5003
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/